### ISSUE TITLE
Beta Todo List

### ISSUE THREAD

**Issue by mattstrayer** [lowercase-app/django-taxtea#1]
- [x] Emit signal when zipcode's tax rate changes
- [x] Implement & expose modules main function `getRateForZipCode(zipCode: str)`
- [ ] Build & package
- [x] Handle 429 from Avalara 
- [x] Look into USPS rate limits
- [x] Put Index on zipcodes
- [x] Add Tests
- [x] Throw Exception for USPS Errors
- [x] Add Readme Docs
